### ISSUE TITLE
Missing route

### ISSUE THREAD

**Issue by thomasgatt** [dereuromark/CakePHP-DatabaseLog#16]
Thank you for your work.

I downloaded your plugin via composer and installed it completely. I've loaded the plugin with routes => true and managed to load 'database-log/logs'. However when I try to access 'Details' or 'Delete' I get the following:

Error: A route matching "array ( 'controller' => 'Users', 'action' => 'login', 'plugin' => NULL, 'prefix' => 'admin', '_ext' => NULL, )" could not be found.

I get the above when I try to access: admin/database-log/logs/view/37

Seems to be an issue with Auth. I managed to solve it by adding the following in the LogsController of your plugin;
public function beforeFilter(Event $event) {
		if ($this->Auth->User('role_id') == 1)
			$this->Auth->allow(['logs', 'index', 'view', 'delete']);
  }

However I'm not sure if this is the right way to handle it.

Running cakephp v 3.3.16

**Comment by dereuromark** [comment]
It is an Auth issue, you are not properly setting your auth login url :) Resetting prefix and plugin parts.

**Comment by thomasgatt** [comment]
I managed to sort that, thank you.
