### ISSUE TITLE
Unit-Testing doesn't seem to work

### ISSUE THREAD

**Issue by liviascapin** [dereuromark/CakePHP-DatabaseLog#20]
Hi!

I use this plugin and a slightly altered version of the cakephp-app template and the ``testMissingTemplateInDebug()`` https://github.com/cakephp/app/blob/master/tests/TestCase/Controller/PagesControllerTest.php#L75 test fails on me.

I think it might be because a missingTemplate Exception is thrown (deliberately), which starts this database log plugin, but it's looking for a test-log datasource configuration:
``Cake\Datasource\Exception\MissingDatasourceConfigException: The datasource configuration "test_database_log" was not found.``
That config doesn't seem to exist.

How can we fix that, how can we ensure the test_database_log config does indeed exist?
We could add the test_database_log connection in your bootstrap.php, just like we do with database_log, but I'm not sure that is the way to go. Do you have any insight on this? Except Disabling databaselog for testing https://github.com/dereuromark/CakePHP-DatabaseLog/tree/master/docs#disabling-for-tests. :)

**Comment by dereuromark** [comment]
Thats why there is this part in the docs, for testing I recommend disabling for now.
If you find a better solution let me know!

**Comment by dereuromark** [comment]
Actually, there is a simple way.
In your /tests/bootstrap.php just add this:
```
ConnectionManager::config('test_database_log', [
	'className' => 'Cake\Database\Connection',
	'driver' => 'Cake\Database\Driver\Sqlite',
	'database' => LOGS . 'database_log.sqlite',
	'encoding' => 'utf8',
	'cacheMetadata' => true,
	'quoteIdentifiers' => true,
]);
```
