### ISSUE TITLE
Fatal error on logging with uploads

### ISSUE THREAD

**Issue by hammertime44** [dereuromark/CakePHP-DatabaseLog#29]
Hi. I'm having trouble using the plugin with the friendsofcake/upload plugin. I'm getting the error below.

Fatal error: Allowed memory size of 2151677952 bytes exhausted (tried to allocate 20480 bytes) in /var/www/mydevsys/vendor/cakephp/cakephp/src/ORM/Marshaller.php on line 75

I tried increasing the memory limit but this increased the execution time and the error persisted. I'm using MySql to log the messages. Please assist.

**Comment by dereuromark** [comment]
Are u sure the logging is the problem? What if u disable the db logging?

**Comment by hammertime44** [comment]
The error does not appear when I revert to file logging. Strangely, I'm not logging anything in my file upload method. Perhaps there's default logging for all actions?

**Comment by dereuromark** [comment]
No some error must happen then. Maybe invalid db credentials. stack trace should tell u more.

**Comment by hammertime44** [comment]
The credentials are fine and am able to log in other actions. However, this particular action accepts a json request with a file attachment throws the error below:

<br />
<b>Fatal error</b>:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 16384 bytes) in <b>/var/www/mcaz_ctr_dev/vendor/dereuromark/cakephp-databaselog/src/Model/Table/DatabaseLogsTable.php</b> on line <b>69</b><br />
<br />
<b>Fatal error</b>:  Allowed memory size of 2151677952 bytes exhausted (tried to allocate 262144 bytes) in <b>/var/www/mcaz_ctr_dev/vendor/cakephp/cakephp/src/ORM/Marshaller.php</b> on line <b>281</b><br />

**Comment by dereuromark** [comment]
aha, so the blob file data might be the cause.

**Comment by hammertime44** [comment]
Not logging anything in my action (below). I suspect the upload plugin may be logging something automatically. 

public function addAttachments()
    {
        $application = $this->Applications->get($this->request->getData('foreign_key'), ['contain' => [], 'fields' => ['id', 'user_id']]);
        if (empty($application)) {
            $this->response->body('Failure');
                $this->response->statusCode(403);
                $this->set([
                        'errors' => 'The application does not exist',
                        'message' => 'Failure', 
                        '_serialize' => ['errors','message']]);
                    return;
        }

        //$category = $this->request->getData();
        if ($this->request->is('post')) {
            $application = $this->Applications->patchEntity($application, $this->request->getData());
            if ($this->Applications->save($application)) {
                $this->set([
                        'message' => 'Success', 
                        //'category' => $category,
                        'content' => $application['attachments'],
                        '_serialize' => ['message', 'content', 'category']]);
                    return;
            } else {
                $this->response->body('Failure');
                $this->response->statusCode(403);
                $this->set([
                        'errors' => $application->errors(),
                        'message' => 'Failure', 
                        '_serialize' => ['errors','message']]);
                    return;
            }
        }
        $this->set(compact('application'));
        $this->set('_serialize', ['application']);
    }
