### ISSUE TITLE
Missing Controller Error

### ISSUE THREAD

**Issue by die7fox** [dereuromark/CakePHP-DatabaseLog#38]
Running version 3.0.0 of this plugin on CentOS 7 in CakePHP 4.1.3. Followed the installation/configuration instructions. Plugin is loaded with 'routes' => true option. The Friends of Cake "Search" plugin is also loaded. When I try to load `localhost/admin/database-log/logs`, I get the following error:

`DatabaseLog.LogsController could not be found`

The LogsController is present, however.

When I just load `localhost/admin/database-log`, I can see the error log entries. I cannot , however, use any of the filters or any of the actions (Remove Duplicates, Reset Logs) without getting the following error:

`Search.PrgComponent could not be found.`

I'm guessing that's because I should be loading `admin/database-log/logs` instead of `admin/database-log`. Can you suggest what I should look for to fix this?

**Comment by dereuromark** [comment]
Prg was renamed to Search. Maybe you can make a pr?

**Comment by die7fox** [comment]
Perhaps. I will try that. Can I do anything about the problem of the missing LogsController? It's definitely there, and I haven't made any changes to your original setup, but for some reason, my project can't see it.

**Comment by dereuromark** [comment]
I never released the updates/fixes in master, so far it was still beta
https://github.com/dereuromark/CakePHP-DatabaseLog/releases/tag/3.0.0 should now fix all that.

**Comment by die7fox** [comment]
Awesome. Many thanks. It's a great plugin and solves a lot of my tracking problems.
