### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by kyleobrien91** [dereuromark/CakePHP-DatabaseLog#8]
I think I may go crazy - but just slightly.

So, I've loaded the plugin, setup the CakeLog config and I'm trying rather desperately to get this to work.
```
CakePlugin::load('DatabaseLog');
App::uses('CakeLog', 'Log');
CakeLog::config('default', array('engine' => 'DatabaseLog.Database'));
```

And yet, any request to my app results in a 502 gateway. 

I know you'll ask the "is this guy being an idiot questions". So, as a process of elimination:
- everything with my nginx config is fine (I think)
- commenting the line ```CakeLog::config('default', array('engine' => 'DatabaseLog.Database'));``` results in my app working 100% again
- There is no error output in the nginx error log other than
```
2015/03/12 21:48:55 [error] 70781#0: *258 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: dev.katalog.co.za, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XXXXXX.co.za"
```
- Also, yep, I did configure APP/Config/database_log.php

My CakePHP version is 2.6.2

Aaaaany idea what might be causing it?

**Comment by dereuromark** [comment]
Mabe you missed
```php
$config = array(
    'DatabaseLog' => array(
        'write' => 'default', // DataSource to write to.
        'read' => 'default', // DataSource to read from.
    )
);
```

Note that in this case it would use the default datasource (the DB connection your app by default runs with. Also make sure that you created the necessary tables.

**Comment by kyleobrien91** [comment]
@dereuromark - are you referring to the contents of APP/Config/database_log.php? Sorry, I should've been more specific in my original request. Here's what mine looks like:
```
<?php

$config = array(
    'DatabaseLog' => array(
        'write' => 'default', // DataSource to write to.
        'read' => 'default', // DataSource to read from.
    )
);
```

Also created the ```logs``` table with - generated by ```cake schema create --plugin DatabaseLog```
```
CREATE TABLE `logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(50) NOT NULL,
  `message` text NOT NULL,
  `created` datetime DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `hostname` varchar(50) DEFAULT NULL,
  `uri` varchar(255) DEFAULT NULL,
  `refer` varchar(255) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `number` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

```

But with no luck - :(
