### ISSUE TITLE
working with AuthComponent 

### ISSUE THREAD

**Issue by hkosmidi** [dereuromark/CakePHP-DatabaseLog#9]
Hello there,

nice plugin. I am curious how can it be used with AuthComponent. In Plugin/DatabaseLog/Controllers I added a befreFilter function with $this->Auth->allow();

If I update the plugin through composer, won't these files be overwritten? Is there a way not to do so?

**Comment by dereuromark** [comment]
You mean "without" Auth? because it works out of the box with some Auth.

**Comment by hkosmidi** [comment]
Well sorry for my english. I meant using the plugin even if I have AuthComponent loaded.
What do you mean works out of the box? Shouldn't have somewhere a $this->Auth->allow? 
Eventually what I did is writing some code in AppController:beforeFilter :
if ($this->request->params['plugin'] === 'database_log')
            $this->Auth->allow();

Else it redirected my to /users/login.

**Comment by dereuromark** [comment]
allow() would only make sense if you want the info publically accessible, which doesnt make sense for most apps.
Either way, you can easily set either allow or the rights management via AppController, exactly.
